name = "DataUtils"
uuid = "d2f83e56-b19b-43fe-8ada-5b68c2be2945"
authors = ["Daniel Fitze <daniel.fitze@psy.unibe.ch>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
